#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stddef.h>

#define APP_PAYLOAD_MAX_LEN 512U

#define APP_PACKET_HEADER 0xE55EU
#define APP_PACKET_HEADER_LEN 6U
#define APP_PACKET_CRC_LEN 4U
#define APP_PACKET_OVERHEAD (APP_PACKET_HEADER_LEN + APP_PACKET_CRC_LEN)
#define APP_PACKET_MAX_LEN (APP_PACKET_OVERHEAD + APP_PAYLOAD_MAX_LEN)

#define APP_RADIO_TX_QUEUE_LEN 20U
#define APP_SERIAL_COMMAND_QUEUE_LEN 8U

#define APP_CH9434_UART_COUNT 4U
#define APP_CH9434_RX_BUFFER_LEN APP_PAYLOAD_MAX_LEN
#define APP_CH9434_POLL_INTERVAL_MS 10U
#define APP_RFID_POLL_INTERVAL_MS 500U

#define APP_QUEUE_SEND_TIMEOUT_MS 1000U

#define APP_RADIO_RX_TIMEOUT_MS 200U
#define APP_RADIO_RESET_PERIOD_MS (10U * 60U * 1000U)

#define APP_RS485_DIR_SETTLE_MS 1U
#define APP_RS485_TX_DONE_TIMEOUT_MS 200U
#define APP_RS485_TX_HOLD_MIN_MS 10U

#define APP_TASK_STACK_LARGE 8192U
#define APP_TASK_STACK_DEFAULT 6144U

#endif // APP_CONFIG_H
