idf_component_register(
    SRCS
        "main.c"
        "app_protocol.c"
        "app_protocol_stream.c"
        "board.c"
        "cellular_service.cc"
        "ch9434.c"
        "e34_2g4d20d.c"
        "gnss_ml307c.c"
        "onenet_config.c"
        "onenet_ota_protocol.c"
        "onenet_ota_service.cc"
        "onenet_reply.c"
        "onenet_time.c"
        "onenet_token.c"
        "radio_service.c"
        "rfid_response.c"
        "rfid_store.c"
        "serial_router.c"
    INCLUDE_DIRS "."
    REQUIRES
        app_update
        esp_driver_spi
        esp_ml307
        esp_partition
        json
        mbedtls
        nvs_flash
)
